### ISSUE TITLE
Debugger fails with textual cbmc output

### ISSUE THREAD

**Issue by markrtuttle** [model-checking/cbmc-proof-debugger#2]
The debugger fails when run on the output of cbmc-viewer when cbmc-viewer was run on the textual output of cbmc.

To reproduce, build any of the FreeRTOS proofs using the legacy starter kit:

```
git clone https://github.com/FreeRTOS/FreeRTOS-Plus-TCP.git
cd FreeRTOS-Plus-TCP
git submodule update --init --checkout --recursive
cd test/cbmc/proofs
./prepare.py 
cd ARP/ARPAgeCache
make
```

This runs cbmc in text mode without the `--xml-ui` flag and produces cbmc.txt instead of cbmc.xml.

Now start up code, load the traces, and start the debugger.  

The debugger fails in [`simulatorState.addAssignment`](https://github.com/model-checking/cbmc-proof-debugger/blob/0785d69f7043a68fe3bce9a6bf85147e85d346fd/src/simulatorState.ts#L153) while trying to [parse the scope](https://github.com/model-checking/cbmc-proof-debugger/blob/0785d69f7043a68fe3bce9a6bf85147e85d346fd/src/simulatorState.ts#L155) of the left-hand side of the assignment because the scope is null.  This invocation of addAssignment occurs while [simulating an assignment step](https://github.com/model-checking/cbmc-proof-debugger/blob/0785d69f7043a68fe3bce9a6bf85147e85d346fd/src/simulatorTrace.ts#L118). The null value arises because the [scope is taken](https://github.com/model-checking/cbmc-proof-debugger/blob/0785d69f7043a68fe3bce9a6bf85147e85d346fd/src/simulatorTrace.ts#L116) from `lhs-lexical-scope` in the trace step.

The problem is that when cbmc-viewer is scanning the traces produced by cbmc, viewer finds a value for `lhs-lexical-scope` when [parsing xml output](https://github.com/model-checking/cbmc-viewer/blob/f435f3f075b6cee95609f2f7138cad836c4c6192/src/cbmc_viewer/tracet.py#L409) of cbmc not when [parsing text output](https://github.com/model-checking/cbmc-viewer/blob/f435f3f075b6cee95609f2f7138cad836c4c6192/src/cbmc_viewer/tracet.py#L255) or [parsing json output](https://github.com/model-checking/cbmc-viewer/blob/f435f3f075b6cee95609f2f7138cad836c4c6192/src/cbmc_viewer/tracet.py#L544).  The problem is that this scope simply isn't present in the textual output of cbmc.

**Comment by karkhaz** [comment]
Thank you. I wonder what the impact of this is? Are there specific authors of the FreeRTOS repository who are attempting to use the debugger?

It seems reasonable to me for the debugger to assume the presence of certain files that are emitted from the [more widely-used starter kit](https://github.com/model-checking/cbmc-starter-kit/). If the FreeRTOS's custom starter kit doesn't write these files out, then it seems like FreeRTOS should be fixed (e.g. add `--xml-ui`). I'm not convinced that we should fix anything up in the debugger.

Could you clarify what you're expecting here? As you point out, the debugger cannot use the text output, the only option is to give it XML. I'm inclined to close this issue, and possibly create one on FreeRTOS if it's causing any actual pain.

**Comment by markrtuttle** [comment]
This bug report comes from a FreeRTOS developer trying to debug proof issues.  I proposed to him that, as a short-term solution, I think it should be fairly easy to modify prepare.py to generate a Makefile that produces and consumes xml output.

**Comment by karkhaz** [comment]
Thank you. I'll see if we can fix FreeRTOS's starter kit in a more permanent way. Keeping this issue open until then.

**Comment by markrtuttle** [comment]
Applying this patch file [makefile.patch](https://github.com/model-checking/cbmc-proof-debugger/files/10395405/makefile.patch) to Makefile.template appears to solve the problem.  Maybe we could apply this patch file in all of the legacy FreeRTOS and FreeRTOS-Plus-TCP proof repositories.

This patch has the side effect of renaming the report directory from the old `html` to the modern `report` name.

**Comment by karkhaz** [comment]
OK, I posted PRs for [FreeRTOS/FreeRTOS-Plus-TCP](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/673) and [FreeRTOS/FreeRTOS/](https://github.com/FreeRTOS/FreeRTOS/pull/912)

**Comment by markrtuttle** [comment]
Closed by https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/673 and https://github.com/FreeRTOS/FreeRTOS/pull/912
